FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY springboot/pom.xml .
COPY springboot/src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

COPY --from=build /app/target/shadownet-nexus-1.0.0.jar app.jar

EXPOSE 3001

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
